# The URL the site will be built for
base_url = "https://titaneric.github.io"
title = "titaneric"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feeds = false
feed_filenames = ["rss.xml"]
default_language = "en"
theme = "apollo"

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
theme = "toggle"
# Put all your custom variables here
menu = [
    { url = "/", name = "Home" },
    { url = "/tags", name = "Tags" },
    { url = "/categories", name = "Categories" },
    # { url = "$BASE_URL/yew-examples/", name = "Yew Examples" },
    { url = "/pdfs/resume.pdf", name = "Resume" },
]
mathjax = true
mathjax_dollar_inline_enable = true

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/chen-yi-huang/", icon = "linkedin" },
    { name = "github", url = "https://github.com/titaneric/", icon = "github" },
]
toc = true
build_search_index = true
favicon = "/icons/favicon-16x16.png"
fancy_code = true
dynamic_note = true
comment = false

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra.analytics]
enabled = false
