base_url = "https://www.titaneric.com"
title = "titaneric"

compile_sass = true
generate_feeds = false
feed_filenames = ["rss.xml"]
default_language = "en"
theme = "apollo"

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"
external_links_no_referrer = true

[extra]
theme = "toggle"
menu = [
    { url = "/posts", name = "posts" },
    { url = "/tags", name = "tags" },
    { url = "/categories", name = "categories" },
    { url = "/archive", name = "archive" },
    { url = "/pdfs/resume.pdf", name = "about" },
    { url = "/notes/index.html", name = "notes" },
]
mathjax = true
mathjax_dollar_inline_enable = true

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/chen-yi-huang/", icon = "linkedin" },
    { name = "github", url = "https://github.com/titaneric/", icon = "github" },
]
toc = true
favicon = "/icons/favicon-16x16.png"
fancy_code = true
dynamic_note = true
comment = false
repo_view = true
repo_url = "https://github.com/titaneric/titaneric.github.io/tree/master/content/"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra.analytics]
enabled = true

[extra.analytics.umami]
website_id = "63f9d7c5-7c47-493b-af29-481374c7531c"

# [languages.zh]
# generate_feeds = true                                     # there will be a feed for French content
# build_search_index = true
# taxonomies = [{ name = "categories" }, { name = "tags" }]
