# On every push this script is executed
on: push
name: Build and deploy GH Pages
permissions:
  contents: write
jobs:
  get_resume:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: typst-community/setup-typst@v4
      id: setup-typst

    - name: Compile resume by typst
      run: |
        typst compile static/latex/resume.typ static/pdfs/resume.pdf

    - name: Get changed files
      id: changed-files
      uses: dorny/paths-filter@v2
      with:
        base: HEAD
        filters: |
          typst_dest:
          - static/pdfs/**
        
    - name: commit downloaded resume
      if: steps.changed-files.outputs.typst_dest == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update resume by bot
        file_pattern: 'static/pdfs/resume.pdf'
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    needs: get_resume
    steps:
    # Checkout
    - uses: actions/checkout@v4
      with:
        ref: "master"
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PVT_KEY }}
        owner: ${{ github.repository_owner }}
    # Build and deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        GITHUB_TOKEN: ${{steps.app-token.outputs.token}}
        # CHECK_LINKS: true
    - name: Dispatch the notes to deploy itself
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ steps.app-token.outputs.token }}
        repository: titaneric/notes
        event-type: deploy-again