# On every push this script is executed
on: push
name: Build and deploy GH Pages
permissions:
  contents: write
jobs:
  get_resume:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - uses: actions/checkout@master

    - uses: yusancky/setup-typst@v2
      id: setup-typst
      with:
        version: 'v0.9.0'

    - name: Compile resume by typst
      run: |
        typst compile static/latex/resume.typ static/pdfs/resume.pdf

    - name: Get changed files
      id: changed-files
      uses: dorny/paths-filter@v2
      with:
        base: HEAD
        filters: |
          typst_dest:
          - static/pdfs/**
        
    - name: commit downloaded resume
      if: steps.changed-files.outputs.typst_dest == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update resume by bot
        file_pattern: 'static/pdfs/resume.pdf'
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    needs: get_resume
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build and deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
    # - name: Dispatch the mdbook to deploy itself
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.TOKEN }}
    #     repository: titaneric/yew-examples
    #     event-type: deploy-again
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'