# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  get_resume:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - uses: actions/checkout@master
    - name: Download resume from latexonline.cc
      run: |
        wget https://github.com/typst/typst/releases/download/v0.4.0/typst-x86_64-unknown-linux-musl.tar.xz
        tar -xvf typst-x86_64-unknown-linux-musl.tar.xz
        chmod +x ./typst-x86_64-unknown-linux-musl/typst
        ./typst-x86_64-unknown-linux-musl/typst -v compile static/latex/resume.typ
        mv -v static/latex/resume.pdf static/pdfs
        stat static/pdfs/resume.pdf
    - name: commit downloaded resume
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update resume by bot
        file_pattern: 'static/pdfs/*.pdf'
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    # needs: get_resume
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build and deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.16.1-1
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
    # - name: Dispatch the mdbook to deploy itself
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.TOKEN }}
    #     repository: titaneric/yew-examples
    #     event-type: deploy-again
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'