# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build and deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
    # - name: Dispatch the mdbook to deploy itself
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.TOKEN }}
    #     repository: titaneric/yew-examples
    #     event-type: deploy-again
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  get_resume:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - name: Download resume from latexonline.cc
      run: |
        curl -O resume.pdf https://latexonline.cc/compile?url=https://raw.githubusercontent.com/titaneric/titaneric.github.io/master/static/latex/resume.tex&command=xelatex
        stat resume.pdf
    # (deprecated) get overleaf compiled pdf by playwright
    # - uses: actions/checkout@master
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10' 
    # - name: install dependencies
    #   run: |
    #     pip install -r scripts/requirements.txt
    #     playwright install chromium
    # - name: download resume
    #   run: |
    #     python scripts/resume.py
    #     stat resume.pdf
    #     mv resume.pdf static/pdfs
    #   env:
    #     ACCOUNT: ${{ secrets.ACCOUNT }}
    #     PASSWORD: ${{ secrets.PASSWORD }}
    #     DOCID: ${{ secrets.DOCID }}
    #     PROJID: ${{ secrets.PROJID }}
    #     TIMEOUT: 60000
    # - name: commit downloaded resume
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: Update resume by bot
    #     file_pattern: 'static/pdfs/*.pdf'