# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build and deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
    # - name: Dispatch the mdbook to deploy itself
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.TOKEN }}
    #     repository: titaneric/yew-examples
    #     event-type: deploy-again
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
  get_resume:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: install dependencies and download resume
      run: |
        cd scripts
        ls
        pip install -r requirements.txt
        playwright install chromium
        python resume.py
        stat resume.pdf
      env:
        ACCOUNT: $ACCOUNT
        PASSWORD: $PASSWORD
        DOCID: $DOCID
        PROJID: $PROJID